---
title: "Gov 50 Final Project"
author: "Ananya Choudhary"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thought

Is female representation in the parliament of a country a direct result of their access to education?
The direct correlation between women's representation in parliamentary bodies and their access to education is a well-documented and essential aspect of gender equality. Access to education equips women with the knowledge, skills, and confidence necessary to participate actively in the political sphere. Education can empower women to understand their rights, engage in public discourse, and navigate complex policy issues effectively. By investing in women's education, nations are not only fostering greater political inclusivity but also reaping the benefits of a more diverse and informed decision-making process. As women gain access to quality education, they are more likely to break through traditional gender roles and stereotypes, ultimately leading to increased female participation in political leadership positions, which is vital for a more equitable and representative democracy. My hypothesis is that as the access to education for women increases, their political representation also increases. My sample consists of two dataseets from the UN about all the member countries' seats held by women in the parliament and the gender ratio in access to education. For the project I will be focusing on South Asian countries. If I find that as the education level over the years of women in South Asian country increases alongside their political representation then it will support my hypothesis.  



```{r}
library(tidyverse)
library(janitor)
df <- read_csv("data/SYB65_317_202209_Seats held by women in Parliament.csv", skip = 1) |>
  janitor::clean_names() |> 
  rename(country = x2) 

only_countries <- df |>
  filter(country == "India"| country =="Pakistan"|country =="China"|country =="Bangladesh"|country=="Nepal")

ggplot(data = only_countries, mapping=aes(x=year, y=value, color = country, fill = country)) + geom_point() + geom_smooth(method = "lm", se = FALSE) + facet_wrap(~country) 

```


